### ISSUE TITLE
cs9.wac.phicdn.net is a CNAME for oscp.digicert.com

### ISSUE THREAD

**Issue by p1r473** [ftpmorph/ftprivacy#12]
cs9.wac.phicdn.net is a CNAME for oscp.digicert.com
This breaks anything that uses DigiCert as a CA if you use deep packet inspection for your adblocker

**Comment by ftpmorph** [comment]
Will fix this now thank you for the report.

**Comment by ftpmorph** [comment]
@p1r473 this domain is now commented out of both lists that included it. Thank you for helping to improve the lists!
