### ISSUE TITLE
Is aidc.apple.com needed for macOS verification?

### ISSUE THREAD

**Issue by sjhgvr** [ftpmorph/ftprivacy#6]
Can you verify this please?

https://www.reddit.com/r/pihole/comments/m9uj9n/dbloisdnl_why_is_it_blocking_aidcapplecom/

Thanks

**Comment by ftpmorph** [comment]
Hey thanks for bringing this to my attention.

I have just deleted that blocklist as it is no longer necessary.

I will paste the note I added to the commit where I deleted it for further clarification:

> This list was intended to block domains Apple whitelisted on OS level so Little Snitch etc could not block them.
> 
> Apple has since removed this OS level whitelist of their own domains so Little Snitch and similar work normally again.
> 
> As such there is no longer any need for this list and I am removing it to ensure it does not cause issues with anyone's Apple devices.

Now it is removed, anyone who had added it will see the domains within removed from their blocklists (unless they have another list containing those domains) next time their Pi Hole updates its database.

This is now resolved. Thanks again for bringing it to my attention. I have been focusing my efforts lately on creating new regex blocklists for AdGuard Home so have not been giving the domain lists priority as before.
