### ISSUE TITLE
msh.amazon.com

### ISSUE THREAD

**Issue by p1r473** [ftpmorph/ftprivacy#7]
Hi @ftpmorph 
This domain seems to break thumbnails for items in certain parts of the Amazon app

**Comment by ftpmorph** [comment]
Can you show examples so I can reproduce this issue? I use the Amazon app often with this filter in place and thumbnails always load fine for me.

**Comment by p1r473** [comment]
Cant reproduce it at the moment, will reopen if I can
Thanks!
