### ISSUE TITLE
graph.microsoft.com

### ISSUE THREAD

**Issue by p1r473** [ftpmorph/ftprivacy#8]
I believe this is a false positive. It is required for office/SharePoint and breaks Office applications
![image](https://user-images.githubusercontent.com/9235633/123322921-da0f0380-d502-11eb-971f-b284929aca26.png)

Also, this is the only blocklist, out of my 800 blocklists, blicking this domain
@ftpmorph

**Comment by ftpmorph** [comment]
To quote Microsoft itself:

> Microsoft Graph is the gateway to data and intelligence in Microsoft 365. It provides a unified programmability model that you can use to access the tremendous amount of data in Microsoft 365, Windows 10, and Enterprise Mobility + Security. Use the wealth of data in Microsoft Graph to build apps for organizations and consumers that interact with millions of users.
> 
> ...
> 
> The Microsoft Graph API offers a single endpoint, https://graph.microsoft.com, to provide access to rich, people-centric data and insights in the Microsoft cloud
> 
> ...
> 
> Together, the Microsoft Graph API, connectors (preview), and Data Connect power the Microsoft 365 platform. With the ability to access Microsoft Graph data and other datasets, you can derive insights and analytics, extend Microsoft 365 experiences, and build unique, intelligent applications.

Source: https://docs.microsoft.com/en-us/graph/overview

This is clearly marketed as an analytics tool hence its inclusion on the list.

If it breaks things in your use case of course you are free to whitelist it, but for what it's worth I use Microsoft Office 365 on my company issued laptop daily and never run into issues sharing documents.

I'm leaning towards keeping this in as Microsoft very obviously use this for collecting usage data as part of their analytics platform and I cannot reproduce the reported issue myself.

But of course by all means whitelist it if it causes problems for your setup.

**Comment by p1r473** [comment]
Thank you, that works!
