### ISSUE TITLE
some more on the current hosts being called from the xiaomi mobiles

### ISSUE THREAD

**Issue by netahoy** [ftpmorph/ftprivacy#9]
and these showup quite often in my logs since the new buy.... as of 20210914, might be good contenders for your Xiaomi list

```
tracking.india.miui.com
api.aurogon.intl.miui.com
jupiter.intl.sys.miui.com
idmb.register.xmpush.global.xiaomi.com
i2.api.io.mi.com
# obvious updates
update.intl.miui.com
```

**Comment by ftpmorph** [comment]
Added these domains to the domains and regex lists, added update domain to regex whitelist. Thank you for sharing!
